### ISSUE TITLE
Feature Request: option to add a marker on the 80th column

### ISSUE THREAD

**Issue by joelgrimberg** [loctvl842/monokai-pro.nvim#119]
In VsCode I am used to have a 'marker' on the 80th column.
Would be great to have this option in Monokai ;) 

Since I am new in the (Lazy)Vim, at this moment I do not know how to fix this myself.

**Comment by loctvl842** [comment]
Is that like this one:

![image](https://github.com/loctvl842/monokai-pro.nvim/assets/80513079/a03d6f94-3acc-467a-901c-38bf49509bb9)


If so, you just need to `set colorcolumn=80`

**Comment by joelgrimberg** [comment]
thanx for the reply!
so my question is, where should I set this and is this stylable? (like making the line red)
afaik the monokai theme overrides all default styling (like styling that is set in .vimrc)

**Comment by joelgrimberg** [comment]
ah, got it already:
vim.opt.colorcolumn = "79"  in lazy.lua

now I only have to figure out how to apply the color.

**Comment by loctvl842** [comment]
You can change the color of colorcolumn by using override provided by my plugin:

```lua
  {
    "loctvl842/monokai-pro.nvim",
      override = function(c)
        return {
          ColorColumn = { bg = c.editor.background },
        }
        end
    }
```

I set the color column to have the same color with my editor's background. Because I don't like using it, you can change it to any color you like. You can reference my [config](https://github.com/loctvl842/nvim/blob/master/lua/beastvim/plugins/colorscheme.lua#L49)

**Comment by joelgrimberg** [comment]
Thanx @loctvl842, problem solved!
